export const ErrorCodes = {
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  CONFLICT: 'CONFLICT',
  LLM_PROVIDER_ERROR: 'LLM_PROVIDER_ERROR',
  IMPORT_PARSE_FAILED: 'IMPORT_PARSE_FAILED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;
